num1=10
num2='10'
num3=10.10
num4='True'

print(num1)
print(num2)
print(num3)
print(num4)
print("****************************")
print(type(num1))
print(type(num2))
print(type(num3))
print(type(num4))
print("###########################")
print(str(num1))
print(int(num2))
print(int(num3))
print(bool(num4))
print("****************************")
print(type(num1))
print(type(num2))
print(type(num3))
print(type(num4))